[phases.build]
cmds = [
  "cd apps/web",
  "npm install",
  "npx prisma generate",
  "npm run build"
]

[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[start]
cmd = "cd apps/web && npx prisma migrate deploy && npm start"
